#!/usr/bin/env python
"""Generate results/alignments/README.md from the produced CSVs. Run after --combine."""
import platform
import subprocess
from pathlib import Path

import numpy as np
import pandas as pd

T12 = Path(__file__).resolve().parent.parent
OUT = T12 / "results" / "alignments"
VENV = T12 / ".venv-tf" / "bin" / "python"

PKGS = ["tensorflow", "tf-keras", "numpy", "scipy", "pandas", "g2p_en",
        "hydra-core", "omegaconf", "matplotlib"]


def versions():
    try:
        txt = subprocess.run([str(VENV), "-m", "pip", "freeze"], capture_output=True,
                             text=True, timeout=120).stdout
    except Exception:
        return "    (pip freeze unavailable)"
    have = {}
    for line in txt.splitlines():
        if "==" in line:
            k, v = line.split("==", 1)
            have[k.lower()] = v
    rows = [f"| {p} | {have.get(p.lower(), '-')} |" for p in PKGS]
    return "\n".join(rows)


def per_table(g):
    cols = ["session", "partition", "modality", "input_layer_from", "own_input_layer",
            "held_out", "n_trials", "n_aligned", "n_phonemes_true", "per"]
    g = g[cols].copy()
    g["per"] = (g["per"] * 100).round(2)
    g = g.rename(columns={"per": "PER_%", "own_input_layer": "own_layer"})
    head = "| " + " | ".join(g.columns) + " |"
    sep = "|" + "---|" * len(g.columns)
    body = "\n".join("| " + " | ".join(str(x) for x in r) + " |"
                     for r in g.itertuples(index=False))
    return "\n".join([head, sep, body])


def main():
    g = pd.read_csv(OUT / "session_per.csv")
    s = pd.read_csv(OUT / "trial_summary.csv")
    seg_files = sorted(p for p in OUT.glob("*.csv")
                       if not p.name.endswith(("_trials.csv", "session_per.csv",
                                               "trial_summary.csv")))
    d = pd.concat([pd.read_csv(f) for f in seg_files], ignore_index=True)

    test = g[g.partition == "test"]
    voc_own = test[test.own_input_layer & (test.modality == "vocal")]
    voc_bor = test[~test.own_input_layer & (test.modality == "vocal")]
    nonvoc = test[~test.own_input_layer & (test.modality == "nonvocal")]

    # full held-out set: test for everyone, plus BOTH partitions of the 5 untrained sessions
    ho = g[g.held_out]
    ho_voc_own = ho[ho.own_input_layer & (ho.modality == "vocal")]
    ho_voc_bor = ho[~ho.own_input_layer & (ho.modality == "vocal")]
    ho_nonvoc = ho[~ho.own_input_layer & (ho.modality == "nonvocal")]

    def wper(x):
        return 100 * x.edit_distance.sum() / x.n_phonemes_true.sum() if len(x) else float("nan")

    def nt(x):
        return int(x.n_trials.sum())

    segw = d.seg_end_bin - d.seg_start_bin
    ctrw = d.rnn_center_end - d.rnn_center_start
    dur = d.rnn_end_step - d.rnn_start_step + 1
    sil_dur = dur[d.phoneme == "SIL"].mean()
    oth_dur = dur[d.phoneme != "SIL"].mean()

    txt = f"""# T12 phoneme-level forced alignments

Phoneme-level CTC forced alignments for the T12 speech BCI dataset (Willett et al. 2023,
Dryad `dryad.x69p8czpq`), produced with the authors' own pretrained baseline RNN
(`derived/rnns/baselineRelease`, checkpoint `ckpt-9950`) running on CPU.

Generated by `scripts/align_t12.py`. Every number below is measured, not estimated.

## 1. What was run

```bash
cd {T12}

# environment (Python 3.12 via `brew install python@3.12`; TF has no 3.14 wheels)
/opt/homebrew/opt/python@3.12/bin/python3.12 -m venv .venv-tf
./.venv-tf/bin/python -m pip install numpy==1.26.4 scipy==1.14.1 pandas \\
    tensorflow==2.18.0 tf-keras==2.18.0 hydra-core==1.3.2 omegaconf \\
    g2p_en==2.1.0 edit_distance==1.0.6 matplotlib
./.venv-tf/bin/python -m pip install --no-deps -e code/speechBCI/NeuralDecoder
./.venv-tf/bin/python -c "import nltk; [nltk.download(p) for p in \\
    ['averaged_perceptron_tagger_eng','cmudict','punkt','punkt_tab']]"

# data
tar -xzf raw/derived.tar.gz -C data --strip-components=1 './derived/rnns/baselineRelease'
tar -xzf raw/derived.tar.gz -C data --strip-components=1 './derived/tfRecords'
# competitionData.tar.gz -> data/competitionData/  (only needed for --source mat)

# alignments: all 24 sessions, train + test
./.venv-tf/bin/python scripts/align_t12.py --sessions all --partitions test train
./.venv-tf/bin/python scripts/align_t12.py --combine
./.venv-tf/bin/python scripts/make_readme.py
```

Other entry points:

```bash
# one session
./.venv-tf/bin/python scripts/align_t12.py --sessions t12.2022.08.13 --partitions test
# raw .mat route instead of tfRecords (identical results, see section 6)
./.venv-tf/bin/python scripts/align_t12.py --source mat --sessions t12.2022.06.23 \\
    --partitions test --input-layer-from t12.2022.06.21
# selectors: all | all-vocal | all-nonvocal | all-trained
```

`TF_USE_LEGACY_KERAS=1` and CPU-only execution are set inside the script; nothing extra
is needed in the shell.

### Versions

| package | version |
|---|---|
{versions()}

Python {platform.python_version()} on {platform.platform()} ({platform.machine()}), CPU only.

## 2. Model, as actually configured

Read from `data/derived/rnns/baselineRelease/args.yaml` at runtime, not hardcoded:

| field | value |
|---|---|
| GRU layers / units | 5 / **1024** |
| input stack | `kernel_size=` **32**, `strides=4` |
| day-specific input layers | **19** (Dense 256 + softsign, one per training session) |
| output classes | 41 = 40 phonemes + blank |
| `smoothInputs` / `smoothKernelSD` | 1 / 2.0 (Gaussian, applied before the input layer) |
| `normLayer` | `false` -> the `Normalization` layers are identity (mean 0, var 1) |
| checkpoint | `ckpt-9950` (latest) |

> **Correction to the original task brief.** The released checkpoint is *not* the repo's
> default `gru_stack_inputNet.yaml`. It uses **1024** units (not 512) and stack
> **kernel_size 32** (not 14). Confirmed independently by the restored layer-0 GRU kernel
> shape `(8192, 3072)` = 32 bins x 256 features by 3 x 1024 gates. All bin arithmetic below
> therefore uses kernel 32, stride 4.

**Class indexing.** `seqClassIDs` in the tfRecords store `PHONE_DEF_SIL.index(p) + 1`, but
`_valStep` subtracts 1 and calls CTC with `blank_index=-1`. So in the **logits**, column
`j` for `j` in 0..39 is `PHONE_DEF_SIL[j]` (39 = `SIL`) and column **40 is blank**. Not
blank=0.

**Step/bin mapping.** Bins are 20 ms. RNN step `s` is computed from input bins
`[4s, 4s+32)`, and `n_steps = (T - 32) // 4 + 1`, matching
`models.GRU.getSubsampledTimeSteps`.

## 3. Method

1. Features: `concat(tx1[:, :128], spikePow[:, :128])` -> 256 dims, blockwise z-scored by
   `blockIdx` (the tfRecords already contain this; the `.mat` route recomputes it).
2. Forward pass: identity `Normalization` -> Gaussian smoothing (SD 2) -> the session's
   day-specific input layer -> 5-layer GRU -> 41 logits per step.
3. Greedy decode (argmax, collapse repeats, drop blank) -> Levenshtein distance against
   the true phoneme sequence -> PER.
4. **Forced alignment**: Viterbi over the standard CTC extended state sequence
   `[blank, l0, blank, l1, ..., l_{{L-1}}, blank]`, with stay / advance / skip transitions
   (skip permitted only into a label state whose label differs from the previous one).
   Implemented in numpy in `ctc_forced_align`.

   The authors' `ctcForcedAlignmentUtils` (ported from the PyTorch tutorial) forces each
   token to occupy exactly one frame, which cannot express phoneme duration, so it was not
   used for the alignment itself. The implementation here lets a label span multiple steps.

5. Each phoneme's occupied steps are mapped to bins (section 4) and labelled with word
   index and position in word, derived from `SIL` positions in the label sequence
   (`SIL` terminates every word).

Batching sorts trials by length to minimise padding. This is exactly equivalent to
per-trial inference here: the GRU is unidirectional, so right padding cannot affect
earlier steps, and because `normLayer` is identity the padded zeros stay zero and match
what `'SAME'` Gaussian padding would insert anyway.

## 4. Output files

### `<session>_<partition>.csv` — one row per phoneme

| column | meaning |
|---|---|
| `session`, `partition`, `modality` | `modality` is `vocal` / `nonvocal` (mouthed) |
| `input_layer_from` | which session's day-specific input layer was used. **If this differs from `session`, the row is APPROXIMATE** |
| `trial_idx` | index within the partition, matching the tfRecord / `.mat` order |
| `sentence` | punctuation-stripped lowercased transcription (the exact string fed to g2p) |
| `phone_idx` | position in the trial's phoneme sequence |
| `phoneme` | ARPAbet, stress stripped; `SIL` marks word ends |
| `word_idx`, `word`, `position_in_word` | `initial` / `medial` / `final` / `single` for real phonemes, `sil` for `SIL`. `single` = one-phoneme word |
| `rnn_start_step`, `rnn_end_step` | inclusive RNN steps the phoneme occupies in the Viterbi path |
| `rnn_center_start`, `rnn_center_end` | **tight window**, half-open bins: `4*s0+16` .. `4*(s1+1)+16` |
| `seg_start_bin`, `seg_end_bin` | **gap-free partition**, half-open bins; blank runs split at their midpoint |
| `start_bin`, `end_bin`, `n_bins` | full receptive field `4*s0` .. `4*s1+32`. Provenance, *not* a duration |
| `score` | mean posterior of that phoneme over its occupied steps |

**Which interval to use.** `rnn_center_*` (median {int(ctrw.median())} bins = {int(ctrw.median())*20} ms) is the
tightest honest window and is the right default for extracting per-phoneme neural
activity. `seg_*` (median {int(segw.median())} bins = {int(segw.median())*20} ms, p5 {int(np.percentile(segw,5))}, p95 {int(np.percentile(segw,95))}) assigns every bin between the first
and last phoneme to exactly one phoneme; use it when you need a complete cover.
`start_bin`/`end_bin` **overlap between neighbours by design**, because consecutive RNN
steps share 28 of their 32 input bins — never read them as phoneme durations.

Verified on every emitted session (assertion runs before each CSV is written): `seg_*` is
strictly positive, contiguous (`seg_end_bin[k] == seg_start_bin[k+1]`), non-overlapping,
and contains the corresponding `rnn_center_*` window.

### Other files

- `<session>_<partition>_trials.csv` — per trial: `n_bins_trial`, `n_rnn_steps`,
  `n_phonemes_true`, `n_phonemes_decoded`, `edit_distance`, `per`, `aligned`,
  `align_logprob`.
- `trial_summary.csv` — all of the above concatenated ({len(s):,} trials).
- `session_per.csv` — the table in section 5.
- `logits/<session>_<partition>_logits.npz` — compressed, one `trial_NNNN` array per
  trial, shape `(n_rnn_steps, 41)`, **float16**. Raw logits, not log-softmaxed.
- `progress.log` — run log.

## 5. Phoneme error rate per session

PER is the greedy-decode Levenshtein distance summed over trials, divided by the total
number of true phonemes. `own_layer = False` marks sessions using a borrowed input layer.

{per_table(g)}

### Summary, `test` partition only

| group | sessions | trials | PER |
|---|---|---|---|
| vocal, own trained input layer | {len(voc_own)} | {nt(voc_own)} | **{wper(voc_own):.2f}%** |
| vocal, borrowed input layer (`07.29`) | {len(voc_bor)} | {nt(voc_bor)} | **{wper(voc_bor):.2f}%** |
| nonvocal (mouthed), borrowed input layer | {len(nonvoc)} | {nt(nonvoc)} | **{wper(nonvoc):.2f}%** |

### Summary, full held-out set

The 5 sessions missing from `args.yaml` were never trained on, so **both** of their
partitions are held out, not just `test`. That multiplies the usable untrained data by
roughly 6x and is the set to use for a confusion analysis:

| group | sessions | trials | PER |
|---|---|---|---|
| vocal, own layer (`test` only — `train` is memorised, excluded) | {len(ho_voc_own)} | {nt(ho_voc_own)} | **{wper(ho_voc_own):.2f}%** |
| vocal, borrowed layer, untrained (`07.29` test+train) | {len(ho_voc_bor)} | {nt(ho_voc_bor)} | **{wper(ho_voc_bor):.2f}%** |
| nonvocal, borrowed layer, untrained (test+train) | {len(ho_nonvoc)} | {nt(ho_nonvoc)} | **{wper(ho_nonvoc):.2f}%** |

Derive `held_out` yourself from the per-phoneme CSVs as
`partition == "test" or input_layer_from != session`.

## 6. Validation

1. **Against the authors' own code.** `NeuralSequenceDecoder.inference()` was run on
   `t12.2022.08.13/test` and compared against this script's inference path:
   authors' `cer` = `0.1487437185929648`, this script = `0.1487437185929648` (identical),
   **max absolute logit difference 1.7e-5** (float32 noise). The forward pass is a faithful
   reproduction.
2. **`.mat` route against the tfRecords.** On `t12.2022.06.23/test`, features derived from
   `competitionData/test/t12.2022.06.23.mat` match the authors' tfRecords to
   **1.9e-6** (float32 storage precision), with phoneme labels and sentences identical in
   40/40 trials and the same PER from both routes. The blockwise z-score and g2p
   reproduction are correct.
3. **Forced alignment on synthetic ground truth.** A hand-built emission matrix with known
   phoneme spans, including an adjacent repeated label (which CTC requires a separating
   blank for), is recovered exactly.
4. **Against the authors' `ctcForcedAlignmentUtils`.** On `t12.2022.08.13/test` (995
   phonemes), both alignments were scored under the same emission matrix. This script's
   path has **strictly higher Viterbi log-probability in 40/40 trials** — as it must, since
   the authors' helper restricts each token to exactly one frame and so searches a subset
   of the valid CTC paths. The two still agree closely on placement: the helper's emission
   frame is within 1 RNN step of this script's occupied span for 82% of phonemes and
   within 2 steps for 94% (median offset 0), with the residual offsets almost all positive,
   reflecting the helper's convention of attaching blank runs to the following token.
5. **Alignment structure.** Checked over all {len(d):,} emitted phonemes in
   {len(s):,} trials: `seg_*` is strictly positive, contiguous and non-overlapping, and
   contains its `rnn_center_*` window, with **0 violations**; steps are monotonic within
   every trial; all 40 phonemes of `PHONE_DEF_SIL` occur; no nulls. `SIL` lands at every
   word end, and `SIL` mean duration is {sil_dur:.1f} steps against {oth_dur:.1f} steps for real
   phonemes, consistent with genuine inter-word pauses.

## 7. Caveats

1. **Do not pool `train` with `test`.** For the 19 training sessions the RNN has
   effectively memorised its `train` partition — PER there runs 0.04-2.5% against 14-33%
   on `test`. Those alignments are still valid *as alignments* (tighter, even, since the
   model fits those sentences), but they carry no information about decoder generalisation
   and a confusion matrix built on them would be meaningless.

   The exception matters: the 5 sessions absent from `args.yaml` were never trained on, so
   their `train` partitions are genuinely held out and show PER in the same range as their
   `test` partitions (e.g. `06.23` train 23.9% vs test 28.3%; `07.29` train 18.2% vs test
   20.5%). Use them. The `held_out` column in `session_per.csv` encodes this.
2. **Borrowed input layers are approximate.** Five sessions are absent from the 19 training
   sessions in `args.yaml` and have no day-specific input layer of their own: the four
   nonvocal days (`06.23`, `08.18`, `08.23`, `08.25`) **and `t12.2022.07.29`, which is
   vocal**. Each borrows the nearest preceding trained session's layer
   (`--input-layer-from` overrides). Filter on `input_layer_from != session`.
   `t12.2022.07.29` is the useful control here: being vocal but untrained, it separates the
   cost of the borrowed layer from the cost of mouthing. It comes out at
   {wper(ho_voc_bor):.2f}% against {wper(ho_voc_own):.2f}% for trained vocal sessions on `test` — i.e. the
   borrowed layer costs close to nothing, so essentially the whole gap to the nonvocal
   sessions ({wper(ho_nonvoc):.2f}%) is attributable to mouthing rather than to the missing input
   layer. That rests on a single control session, so treat it as indicative.
3. **CTC is peaky.** The model emits a phoneme over very few steps and blank elsewhere, so
   the occupied-step span is usually 1 step. Durations in `seg_*` come from splitting the
   intervening blank runs, which is a reasonable convention but not an acoustic measurement.
   These are decoder-derived alignments, not ground-truth articulatory timings; there is no
   audio-based reference in this dataset to validate boundaries against.
4. **`score` is informative and skewed.** Median {d.score.median():.2f}, but 5th percentile
   {d.score.quantile(0.05):.3f} — a minority of phonemes are weakly evidenced. Consider filtering or
   weighting by `score`.
5. **Gaussian input smoothing (SD 2 bins = 40 ms) blurs the step/bin mapping** slightly
   beyond the 32-bin receptive field. Boundaries are not precise to better than a few bins.
6. **`competitionHoldOut` is unlabelled** and therefore cannot be force-aligned; it is
   skipped.
7. Only area 6v is used (first 128 channels of `tx1` and `spikePow`), following the
   authors' baseline. Area 44 is discarded.
"""
    (OUT / "README.md").write_text(txt)
    print(f"wrote {OUT / 'README.md'} ({len(txt)} chars)")


if __name__ == "__main__":
    main()
